# Generated by Django 2.1 on 2018-10-27 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0004_sign'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sign',
            new_name='SignIn',
        ),
    ]
