# Generated by Django 2.1 on 2018-10-27 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0005_auto_20181027_2157'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SignIn',
            new_name='mydata',
        ),
    ]
