# Generated by Django 2.1 on 2018-10-29 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0006_auto_20181027_2202'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register',
        ),
    ]
