# Generated by Django 2.1 on 2018-10-22 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_subuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='subuser',
        ),
    ]
